#!/bin/sh
set -e

if [ -d /run/systemd/system ]; then
    systemctl daemon-reload >/dev/null 2>&1 || true
fi

if [ "$1" = "purge" ]; then
    rm -rf /var/lib/quartz-command
    if getent passwd quartz-command >/dev/null; then
        userdel quartz-command >/dev/null 2>&1 || true
    fi
fi

exit 0
